// i18n core — LANGUAGE = URL (SPEC-ADDENDUM A3, replaces SPEC §4.8).
//
// - A page's language is <html lang>: /x/ is Hebrew, /en/x/ is English (generated by tools/gen-en.mjs from the
//   Hebrew page + the same dictionaries). There is no in-place swap on user action, no i18n.set(), no ?lang=,
//   and `sele:langchange` never fires.
// - i18n.lang     'en' when <html lang="en">, else 'he' (read live, so a QA script can flip <html lang> first).
// - i18n.ready    Promise: common + page runtime dictionary loaded (never rejects).
// - i18n.t(key, vars)  dynamic strings, `{name}` interpolation.
// - i18n.href(path)    '/en' + path on English pages (root-absolute paths, not /assets/), else path.
//                      Every internal link that page JS builds at runtime goes through it.
// - i18n.apply(root)   DOM swap from the loaded dictionaries (+ the gen-en link rule on English pages). The
//                      runtime calls it automatically ONLY on the bilingual 404 (<html data-bilingual>, A3.8).
//
// Loading starts as soon as this module is evaluated (i18n-boot.js imports it first, from <head>):
// /js/i18n/common.js + /js/i18n/<body data-i18n-dict>.js — un-queried URLs, so the modulepreloads match and
// sele.js shares this one instance.

const html = document.documentElement;
const map = Object.create(null);
const warned = new Set();
const HEBREW = /[֐-׿]/;

function currentLang() {
  return (html.getAttribute('lang') || 'he').toLowerCase().startsWith('en') ? 'en' : 'he';
}

// The page dictionary name: <body data-i18n-dict>, or — when this runs before <body> is parsed — the
// /js/i18n/<name>.js modulepreload that sync-partials writes into <head>. null = not knowable yet.
function dictName() {
  const b = document.body;
  if (b) return b.dataset.i18nDict || '';
  for (const l of document.querySelectorAll('link[rel="modulepreload"][href^="/js/i18n/"]')) {
    const m = /^\/js\/i18n\/([a-z0-9-]+)\.js$/.exec(l.getAttribute('href') || '');
    if (m && m[1] !== 'common') return m[1];
  }
  return null;
}

function whenBody() {
  if (document.body) return Promise.resolve();
  return new Promise((r) => document.addEventListener('DOMContentLoaded', r, { once: true }));
}

async function importDict(name) {
  try {
    const mod = await import(`/js/i18n/${name}.js`);
    return mod.default || {};
  } catch (e) {
    console.warn('[i18n] dictionary not loaded:', name, e && e.message);
    return {};
  }
}

async function load() {
  const commonP = importDict('common');
  let name = dictName();
  if (name === null) { await whenBody(); name = dictName(); }
  const [common, page] = await Promise.all([commonP, name ? importDict(name) : {}]);
  Object.assign(map, common);
  for (const k of Object.keys(page)) {
    if (k in map) console.warn('[i18n] duplicate key, page dictionary wins:', k);
    map[k] = page[k];
  }
}

// ---- data-i18n-html sanitizer (A3.7 step 3 whitelist) ----
const ALLOWED = { A: ['href'], BR: [], EM: [], STRONG: [], SPAN: ['class', 'lang'], BDI: ['lang'] };
const SAFE_ORIGINS = ['https://www.instagram.com/', 'https://www.nevo.co.il/', 'https://www.gov.il/']; // A3.7 step 3 (v2)
const safeHref = (h) => typeof h === 'string' && ((h.startsWith('/') && !h.startsWith('//')) || h.startsWith('mailto:') || SAFE_ORIGINS.some((o) => h.startsWith(o)));

function sanitize(str) {
  const tpl = document.createElement('template');
  tpl.innerHTML = String(str);
  const walk = (node) => {
    for (const child of [...node.childNodes]) {
      if (child.nodeType === 3) continue;
      if (child.nodeType !== 1) { child.remove(); continue; }
      walk(child);
      const keep = ALLOWED[child.tagName];
      if (!keep || (child.tagName === 'A' && !safeHref(child.getAttribute('href')))) {
        child.replaceWith(...child.childNodes); // unwrap: keep the text, drop the element
        continue;
      }
      for (const a of [...child.attributes]) if (!keep.includes(a.name)) child.removeAttribute(a.name);
    }
  };
  walk(tpl.content);
  return tpl;
}

function parseAttrSpec(spec) {
  return String(spec || '')
    .split(';')
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => { const i = p.indexOf(':'); return i < 0 ? ['', ''] : [p.slice(0, i).trim(), p.slice(i + 1).trim()]; })
    .filter(([a, k]) => a && k);
}

function each(root, sel, fn) {
  if (root.nodeType === 1 && root.matches(sel)) fn(root);
  root.querySelectorAll(sel).forEach(fn);
}

// gen-en step 5: root-absolute page links get the /en prefix (not //, /assets/, /en/, or files with an extension).
export function enPath(href) {
  if (typeof href !== 'string' || !href.startsWith('/') || href.startsWith('//')) return href;
  if (href.startsWith('/assets/') || href === '/en' || href.startsWith('/en/') || href.startsWith('/en?') || href.startsWith('/en#')) return href;
  const pathOnly = href.split(/[?#]/)[0];
  if (/\.[a-z0-9]+$/i.test(pathOnly)) return href;
  return pathOnly === '/' ? '/en/' + href.slice(1) : '/en' + href;
}

// The Hebrew path of the current page (strip /en), used to point language links back on English pages.
function hebrewPath() {
  if (html.hasAttribute('data-bilingual')) return '/';
  const p = location.pathname.replace(/\/index\.html$/, '/');
  return p.replace(/^\/en(?=\/|$)/, '') || '/';
}

let resolveReady;
const ready = new Promise((r) => { resolveReady = r; });

export const i18n = {
  ready,
  get lang() { return currentLang(); },
  get dir() { return currentLang() === 'en' ? 'ltr' : 'rtl'; },

  has(key) { return key in map; },

  t(key, vars) {
    const entry = map[key];
    if (!entry) {
      if (!warned.has(key)) { warned.add(key); console.warn('[i18n] missing key:', key); }
      return key;
    }
    let s = entry[currentLang()];
    if (s == null || s === '') s = entry.he ?? '';
    if (vars) s = String(s).replace(/\{(\w+)\}/g, (m, name) => (vars[name] != null ? String(vars[name]) : m));
    return s;
  },

  href(path) {
    if (currentLang() !== 'en' || typeof path !== 'string' || !path.startsWith('/') || path.startsWith('/assets/')) return path;
    return enPath(path);
  },

  apply(root = document) {
    const en = currentLang() === 'en';
    const r = root === document ? html : root;
    const mark = (el, v) => { if (en && HEBREW.test(v)) el.setAttribute('lang', 'he'); };

    each(r, '[data-i18n]', (el) => {
      const k = el.getAttribute('data-i18n');
      if (!(k in map)) return;
      const v = this.t(k);
      if (el.textContent !== v) el.textContent = v;
      mark(el, v);
    });
    each(r, '[data-i18n-init]', (el) => {
      const k = el.getAttribute('data-i18n-init');
      if (!(k in map)) return;
      const v = this.t(k);
      if (el.textContent !== v) el.textContent = v;
    });
    each(r, '[data-i18n-html]', (el) => {
      const k = el.getAttribute('data-i18n-html');
      if (!(k in map)) return;
      const v = this.t(k);
      const tpl = sanitize(v);
      if (el.innerHTML !== tpl.innerHTML) el.replaceChildren(tpl.content);
      mark(el, tpl.content.textContent || el.textContent);
    });
    each(r, '[data-i18n-attr]', (el) => {
      for (const [attr, k] of parseAttrSpec(el.getAttribute('data-i18n-attr'))) {
        if (!(k in map)) continue;
        const v = this.t(k);
        if (el.getAttribute(attr) !== v) el.setAttribute(attr, v);
      }
    });

    if (en) {
      each(r, 'a[href]', (a) => {
        if (a.hasAttribute('data-lang-switch')) return;
        const h = a.getAttribute('href');
        const n = enPath(h);
        if (n !== h) a.setAttribute('href', n);
      });
      each(r, '[data-lang-switch]', (a) => {
        a.setAttribute('href', hebrewPath() + (html.hasAttribute('data-bilingual') ? '' : location.search + location.hash));
        a.setAttribute('hreflang', 'he');
        a.setAttribute('lang', 'he');
        a.setAttribute('dir', 'rtl');
        if (a.getAttribute('data-lang-switch') === 'pill') a.textContent = 'לגרסה העברית ←';
        else { a.textContent = 'עב'; a.setAttribute('aria-label', 'עב, גרסה עברית'); }
      });
      if (root === document && html.hasAttribute('data-bilingual') && 'legal.notfound.docTitle' in map) {
        document.title = this.t('legal.notfound.docTitle');
      }
    }
    return root;
  },
};

load().then(() => resolveReady(true), (e) => { console.warn('[i18n]', e); resolveReady(false); });
